version: '3.8'

services:
  churn-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    restart: unless-stopped

  dashboard:
    build: .
    command: streamlit run src/dashboard/dashboard.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    depends_on:
      - churn-api
    restart: unless-stopped

  mlflow:
    image: python:3.9-slim
    command: >
      sh -c "pip install mlflow boto3 && 
             mlflow server --host 0.0.0.0 --port 5000 --default-artifact-root ./mlruns"
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    restart: unless-stopped