model_params:
  rf_params:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
    max_features: "sqrt"
    random_state: 42
    n_jobs: -1

  xgb_params:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.1
    reg_lambda: 0.1
    random_state: 42
    n_jobs: -1

# Training Configuration
training:
  handle_imbalance: true
  validation_split: 0.2

# MLflow Configuration
mlflow:
  experiment_name: "customer_churn_prediction"
  tracking_uri: "http://localhost:5000"
